// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/flight-fetcher/internal/enricher (interfaces: AircraftStore,AircraftLookup,RouteStore,RouteLookup)
//
// Generated by this command:
//
//	mockgen -destination mock_enricher_test.go -package enricher github.com/afreidah/flight-fetcher/internal/enricher AircraftStore,AircraftLookup,RouteStore,RouteLookup
//

// Package enricher is a generated GoMock package.
package enricher

import (
	context "context"
	reflect "reflect"

	airlabs "github.com/afreidah/flight-fetcher/internal/airlabs"
	hexdb "github.com/afreidah/flight-fetcher/internal/hexdb"
	gomock "go.uber.org/mock/gomock"
)

// MockAircraftStore is a mock of AircraftStore interface.
type MockAircraftStore struct {
	ctrl     *gomock.Controller
	recorder *MockAircraftStoreMockRecorder
	isgomock struct{}
}

// MockAircraftStoreMockRecorder is the mock recorder for MockAircraftStore.
type MockAircraftStoreMockRecorder struct {
	mock *MockAircraftStore
}

// NewMockAircraftStore creates a new mock instance.
func NewMockAircraftStore(ctrl *gomock.Controller) *MockAircraftStore {
	mock := &MockAircraftStore{ctrl: ctrl}
	mock.recorder = &MockAircraftStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAircraftStore) EXPECT() *MockAircraftStoreMockRecorder {
	return m.recorder
}

// GetAircraftMeta mocks base method.
func (m *MockAircraftStore) GetAircraftMeta(ctx context.Context, icao24 string) (*hexdb.AircraftInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAircraftMeta", ctx, icao24)
	ret0, _ := ret[0].(*hexdb.AircraftInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAircraftMeta indicates an expected call of GetAircraftMeta.
func (mr *MockAircraftStoreMockRecorder) GetAircraftMeta(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAircraftMeta", reflect.TypeOf((*MockAircraftStore)(nil).GetAircraftMeta), ctx, icao24)
}

// SaveAircraftMeta mocks base method.
func (m *MockAircraftStore) SaveAircraftMeta(ctx context.Context, info *hexdb.AircraftInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAircraftMeta", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAircraftMeta indicates an expected call of SaveAircraftMeta.
func (mr *MockAircraftStoreMockRecorder) SaveAircraftMeta(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAircraftMeta", reflect.TypeOf((*MockAircraftStore)(nil).SaveAircraftMeta), ctx, info)
}

// MockAircraftLookup is a mock of AircraftLookup interface.
type MockAircraftLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAircraftLookupMockRecorder
	isgomock struct{}
}

// MockAircraftLookupMockRecorder is the mock recorder for MockAircraftLookup.
type MockAircraftLookupMockRecorder struct {
	mock *MockAircraftLookup
}

// NewMockAircraftLookup creates a new mock instance.
func NewMockAircraftLookup(ctrl *gomock.Controller) *MockAircraftLookup {
	mock := &MockAircraftLookup{ctrl: ctrl}
	mock.recorder = &MockAircraftLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAircraftLookup) EXPECT() *MockAircraftLookupMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockAircraftLookup) Lookup(ctx context.Context, icao24 string) (*hexdb.AircraftInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, icao24)
	ret0, _ := ret[0].(*hexdb.AircraftInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockAircraftLookupMockRecorder) Lookup(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockAircraftLookup)(nil).Lookup), ctx, icao24)
}

// MockRouteStore is a mock of RouteStore interface.
type MockRouteStore struct {
	ctrl     *gomock.Controller
	recorder *MockRouteStoreMockRecorder
	isgomock struct{}
}

// MockRouteStoreMockRecorder is the mock recorder for MockRouteStore.
type MockRouteStoreMockRecorder struct {
	mock *MockRouteStore
}

// NewMockRouteStore creates a new mock instance.
func NewMockRouteStore(ctrl *gomock.Controller) *MockRouteStore {
	mock := &MockRouteStore{ctrl: ctrl}
	mock.recorder = &MockRouteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteStore) EXPECT() *MockRouteStoreMockRecorder {
	return m.recorder
}

// GetFlightRoute mocks base method.
func (m *MockRouteStore) GetFlightRoute(ctx context.Context, callsign string) (*airlabs.FlightRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightRoute", ctx, callsign)
	ret0, _ := ret[0].(*airlabs.FlightRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightRoute indicates an expected call of GetFlightRoute.
func (mr *MockRouteStoreMockRecorder) GetFlightRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightRoute", reflect.TypeOf((*MockRouteStore)(nil).GetFlightRoute), ctx, callsign)
}

// SaveFlightRoute mocks base method.
func (m *MockRouteStore) SaveFlightRoute(ctx context.Context, route *airlabs.FlightRoute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFlightRoute", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFlightRoute indicates an expected call of SaveFlightRoute.
func (mr *MockRouteStoreMockRecorder) SaveFlightRoute(ctx, route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFlightRoute", reflect.TypeOf((*MockRouteStore)(nil).SaveFlightRoute), ctx, route)
}

// MockRouteLookup is a mock of RouteLookup interface.
type MockRouteLookup struct {
	ctrl     *gomock.Controller
	recorder *MockRouteLookupMockRecorder
	isgomock struct{}
}

// MockRouteLookupMockRecorder is the mock recorder for MockRouteLookup.
type MockRouteLookupMockRecorder struct {
	mock *MockRouteLookup
}

// NewMockRouteLookup creates a new mock instance.
func NewMockRouteLookup(ctrl *gomock.Controller) *MockRouteLookup {
	mock := &MockRouteLookup{ctrl: ctrl}
	mock.recorder = &MockRouteLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteLookup) EXPECT() *MockRouteLookupMockRecorder {
	return m.recorder
}

// LookupRoute mocks base method.
func (m *MockRouteLookup) LookupRoute(ctx context.Context, callsign string) (*airlabs.FlightRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupRoute", ctx, callsign)
	ret0, _ := ret[0].(*airlabs.FlightRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupRoute indicates an expected call of LookupRoute.
func (mr *MockRouteLookupMockRecorder) LookupRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupRoute", reflect.TypeOf((*MockRouteLookup)(nil).LookupRoute), ctx, callsign)
}
