// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/flight-fetcher/internal/enricher (interfaces: AircraftStore,RouteStore)
//
// Generated by this command:
//
//	mockgen -destination mock_enricher_test.go -package enricher github.com/afreidah/flight-fetcher/internal/enricher AircraftStore,RouteStore
//

// Package enricher is a generated GoMock package.
package enricher

import (
	context "context"
	reflect "reflect"

	aircraft "github.com/afreidah/flight-fetcher/internal/aircraft"
	route "github.com/afreidah/flight-fetcher/internal/route"
	gomock "go.uber.org/mock/gomock"
)

// MockAircraftStore is a mock of AircraftStore interface.
type MockAircraftStore struct {
	ctrl     *gomock.Controller
	recorder *MockAircraftStoreMockRecorder
	isgomock struct{}
}

// MockAircraftStoreMockRecorder is the mock recorder for MockAircraftStore.
type MockAircraftStoreMockRecorder struct {
	mock *MockAircraftStore
}

// NewMockAircraftStore creates a new mock instance.
func NewMockAircraftStore(ctrl *gomock.Controller) *MockAircraftStore {
	mock := &MockAircraftStore{ctrl: ctrl}
	mock.recorder = &MockAircraftStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAircraftStore) EXPECT() *MockAircraftStoreMockRecorder {
	return m.recorder
}

// GetAircraftMeta mocks base method.
func (m *MockAircraftStore) GetAircraftMeta(ctx context.Context, icao24 string) (*aircraft.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAircraftMeta", ctx, icao24)
	ret0, _ := ret[0].(*aircraft.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAircraftMeta indicates an expected call of GetAircraftMeta.
func (mr *MockAircraftStoreMockRecorder) GetAircraftMeta(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAircraftMeta", reflect.TypeOf((*MockAircraftStore)(nil).GetAircraftMeta), ctx, icao24)
}

// SaveAircraftMeta mocks base method.
func (m *MockAircraftStore) SaveAircraftMeta(ctx context.Context, info *aircraft.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAircraftMeta", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAircraftMeta indicates an expected call of SaveAircraftMeta.
func (mr *MockAircraftStoreMockRecorder) SaveAircraftMeta(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAircraftMeta", reflect.TypeOf((*MockAircraftStore)(nil).SaveAircraftMeta), ctx, info)
}

// MockRouteStore is a mock of RouteStore interface.
type MockRouteStore struct {
	ctrl     *gomock.Controller
	recorder *MockRouteStoreMockRecorder
	isgomock struct{}
}

// MockRouteStoreMockRecorder is the mock recorder for MockRouteStore.
type MockRouteStoreMockRecorder struct {
	mock *MockRouteStore
}

// NewMockRouteStore creates a new mock instance.
func NewMockRouteStore(ctrl *gomock.Controller) *MockRouteStore {
	mock := &MockRouteStore{ctrl: ctrl}
	mock.recorder = &MockRouteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteStore) EXPECT() *MockRouteStoreMockRecorder {
	return m.recorder
}

// GetFlightRoute mocks base method.
func (m *MockRouteStore) GetFlightRoute(ctx context.Context, callsign string) (*route.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightRoute", ctx, callsign)
	ret0, _ := ret[0].(*route.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightRoute indicates an expected call of GetFlightRoute.
func (mr *MockRouteStoreMockRecorder) GetFlightRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightRoute", reflect.TypeOf((*MockRouteStore)(nil).GetFlightRoute), ctx, callsign)
}

// SaveFlightRoute mocks base method.
func (m *MockRouteStore) SaveFlightRoute(ctx context.Context, arg1 *route.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFlightRoute", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFlightRoute indicates an expected call of SaveFlightRoute.
func (mr *MockRouteStoreMockRecorder) SaveFlightRoute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFlightRoute", reflect.TypeOf((*MockRouteStore)(nil).SaveFlightRoute), ctx, arg1)
}
