// Code generated by MockGen. DO NOT EDIT.
// Source: consumer_interfaces.go
//
// Generated by this command:
//
//	mockgen -source consumer_interfaces.go -destination mock_consumer_interfaces_test.go -package enricher
//

// Package enricher is a generated GoMock package.
package enricher

import (
	context "context"
	reflect "reflect"

	aircraft "github.com/afreidah/flight-fetcher/internal/aircraft"
	route "github.com/afreidah/flight-fetcher/internal/route"
	gomock "go.uber.org/mock/gomock"
)

// MockaircraftMetaReadWriter is a mock of aircraftMetaReadWriter interface.
type MockaircraftMetaReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockaircraftMetaReadWriterMockRecorder
	isgomock struct{}
}

// MockaircraftMetaReadWriterMockRecorder is the mock recorder for MockaircraftMetaReadWriter.
type MockaircraftMetaReadWriterMockRecorder struct {
	mock *MockaircraftMetaReadWriter
}

// NewMockaircraftMetaReadWriter creates a new mock instance.
func NewMockaircraftMetaReadWriter(ctrl *gomock.Controller) *MockaircraftMetaReadWriter {
	mock := &MockaircraftMetaReadWriter{ctrl: ctrl}
	mock.recorder = &MockaircraftMetaReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaircraftMetaReadWriter) EXPECT() *MockaircraftMetaReadWriterMockRecorder {
	return m.recorder
}

// GetAircraftMeta mocks base method.
func (m *MockaircraftMetaReadWriter) GetAircraftMeta(ctx context.Context, icao24 string) (*aircraft.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAircraftMeta", ctx, icao24)
	ret0, _ := ret[0].(*aircraft.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAircraftMeta indicates an expected call of GetAircraftMeta.
func (mr *MockaircraftMetaReadWriterMockRecorder) GetAircraftMeta(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAircraftMeta", reflect.TypeOf((*MockaircraftMetaReadWriter)(nil).GetAircraftMeta), ctx, icao24)
}

// SaveAircraftMeta mocks base method.
func (m *MockaircraftMetaReadWriter) SaveAircraftMeta(ctx context.Context, info *aircraft.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAircraftMeta", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAircraftMeta indicates an expected call of SaveAircraftMeta.
func (mr *MockaircraftMetaReadWriterMockRecorder) SaveAircraftMeta(ctx, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAircraftMeta", reflect.TypeOf((*MockaircraftMetaReadWriter)(nil).SaveAircraftMeta), ctx, info)
}

// MockrouteReadWriter is a mock of routeReadWriter interface.
type MockrouteReadWriter struct {
	ctrl     *gomock.Controller
	recorder *MockrouteReadWriterMockRecorder
	isgomock struct{}
}

// MockrouteReadWriterMockRecorder is the mock recorder for MockrouteReadWriter.
type MockrouteReadWriterMockRecorder struct {
	mock *MockrouteReadWriter
}

// NewMockrouteReadWriter creates a new mock instance.
func NewMockrouteReadWriter(ctrl *gomock.Controller) *MockrouteReadWriter {
	mock := &MockrouteReadWriter{ctrl: ctrl}
	mock.recorder = &MockrouteReadWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrouteReadWriter) EXPECT() *MockrouteReadWriterMockRecorder {
	return m.recorder
}

// GetFlightRoute mocks base method.
func (m *MockrouteReadWriter) GetFlightRoute(ctx context.Context, callsign string) (*route.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlightRoute", ctx, callsign)
	ret0, _ := ret[0].(*route.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlightRoute indicates an expected call of GetFlightRoute.
func (mr *MockrouteReadWriterMockRecorder) GetFlightRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlightRoute", reflect.TypeOf((*MockrouteReadWriter)(nil).GetFlightRoute), ctx, callsign)
}

// SaveFlightRoute mocks base method.
func (m *MockrouteReadWriter) SaveFlightRoute(ctx context.Context, arg1 *route.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFlightRoute", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFlightRoute indicates an expected call of SaveFlightRoute.
func (mr *MockrouteReadWriterMockRecorder) SaveFlightRoute(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFlightRoute", reflect.TypeOf((*MockrouteReadWriter)(nil).SaveFlightRoute), ctx, arg1)
}
