// Code generated by MockGen. DO NOT EDIT.
// Source: consumer_interfaces.go
//
// Generated by this command:
//
//	mockgen -source consumer_interfaces.go -destination mock_consumer_interfaces_test.go -package poller
//

// Package poller is a generated GoMock package.
package poller

import (
	context "context"
	reflect "reflect"
	time "time"

	opensky "github.com/afreidah/flight-fetcher/internal/apiclient/opensky"
	geo "github.com/afreidah/flight-fetcher/internal/geo"
	gomock "go.uber.org/mock/gomock"
)

// MockflightSource is a mock of flightSource interface.
type MockflightSource struct {
	ctrl     *gomock.Controller
	recorder *MockflightSourceMockRecorder
	isgomock struct{}
}

// MockflightSourceMockRecorder is the mock recorder for MockflightSource.
type MockflightSourceMockRecorder struct {
	mock *MockflightSource
}

// NewMockflightSource creates a new mock instance.
func NewMockflightSource(ctrl *gomock.Controller) *MockflightSource {
	mock := &MockflightSource{ctrl: ctrl}
	mock.recorder = &MockflightSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockflightSource) EXPECT() *MockflightSourceMockRecorder {
	return m.recorder
}

// GetStates mocks base method.
func (m *MockflightSource) GetStates(ctx context.Context, bbox geo.BBox) (*opensky.StatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStates", ctx, bbox)
	ret0, _ := ret[0].(*opensky.StatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStates indicates an expected call of GetStates.
func (mr *MockflightSourceMockRecorder) GetStates(ctx, bbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStates", reflect.TypeOf((*MockflightSource)(nil).GetStates), ctx, bbox)
}

// MockflightCache is a mock of flightCache interface.
type MockflightCache struct {
	ctrl     *gomock.Controller
	recorder *MockflightCacheMockRecorder
	isgomock struct{}
}

// MockflightCacheMockRecorder is the mock recorder for MockflightCache.
type MockflightCacheMockRecorder struct {
	mock *MockflightCache
}

// NewMockflightCache creates a new mock instance.
func NewMockflightCache(ctrl *gomock.Controller) *MockflightCache {
	mock := &MockflightCache{ctrl: ctrl}
	mock.recorder = &MockflightCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockflightCache) EXPECT() *MockflightCacheMockRecorder {
	return m.recorder
}

// MarkHeard mocks base method.
func (m *MockflightCache) MarkHeard(ctx context.Context, source, icao24 string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkHeard", ctx, source, icao24, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkHeard indicates an expected call of MarkHeard.
func (mr *MockflightCacheMockRecorder) MarkHeard(ctx, source, icao24, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkHeard", reflect.TypeOf((*MockflightCache)(nil).MarkHeard), ctx, source, icao24, ttl)
}

// SetFlight mocks base method.
func (m *MockflightCache) SetFlight(ctx context.Context, sv *opensky.StateVector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFlight", ctx, sv)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFlight indicates an expected call of SetFlight.
func (mr *MockflightCacheMockRecorder) SetFlight(ctx, sv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlight", reflect.TypeOf((*MockflightCache)(nil).SetFlight), ctx, sv)
}

// MocksightingLogger is a mock of sightingLogger interface.
type MocksightingLogger struct {
	ctrl     *gomock.Controller
	recorder *MocksightingLoggerMockRecorder
	isgomock struct{}
}

// MocksightingLoggerMockRecorder is the mock recorder for MocksightingLogger.
type MocksightingLoggerMockRecorder struct {
	mock *MocksightingLogger
}

// NewMocksightingLogger creates a new mock instance.
func NewMocksightingLogger(ctrl *gomock.Controller) *MocksightingLogger {
	mock := &MocksightingLogger{ctrl: ctrl}
	mock.recorder = &MocksightingLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksightingLogger) EXPECT() *MocksightingLoggerMockRecorder {
	return m.recorder
}

// LogSighting mocks base method.
func (m *MocksightingLogger) LogSighting(ctx context.Context, icao24 string, lat, lon, distanceKm float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSighting", ctx, icao24, lat, lon, distanceKm)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogSighting indicates an expected call of LogSighting.
func (mr *MocksightingLoggerMockRecorder) LogSighting(ctx, icao24, lat, lon, distanceKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSighting", reflect.TypeOf((*MocksightingLogger)(nil).LogSighting), ctx, icao24, lat, lon, distanceKm)
}

// MockaircraftEnricher is a mock of aircraftEnricher interface.
type MockaircraftEnricher struct {
	ctrl     *gomock.Controller
	recorder *MockaircraftEnricherMockRecorder
	isgomock struct{}
}

// MockaircraftEnricherMockRecorder is the mock recorder for MockaircraftEnricher.
type MockaircraftEnricherMockRecorder struct {
	mock *MockaircraftEnricher
}

// NewMockaircraftEnricher creates a new mock instance.
func NewMockaircraftEnricher(ctrl *gomock.Controller) *MockaircraftEnricher {
	mock := &MockaircraftEnricher{ctrl: ctrl}
	mock.recorder = &MockaircraftEnricherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaircraftEnricher) EXPECT() *MockaircraftEnricherMockRecorder {
	return m.recorder
}

// Enrich mocks base method.
func (m *MockaircraftEnricher) Enrich(ctx context.Context, icao24 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrich", ctx, icao24)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enrich indicates an expected call of Enrich.
func (mr *MockaircraftEnricherMockRecorder) Enrich(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrich", reflect.TypeOf((*MockaircraftEnricher)(nil).Enrich), ctx, icao24)
}

// EnrichRoute mocks base method.
func (m *MockaircraftEnricher) EnrichRoute(ctx context.Context, callsign string) (bool, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichRoute", ctx, callsign)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// EnrichRoute indicates an expected call of EnrichRoute.
func (mr *MockaircraftEnricherMockRecorder) EnrichRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichRoute", reflect.TypeOf((*MockaircraftEnricher)(nil).EnrichRoute), ctx, callsign)
}
