// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/flight-fetcher/internal/enricher (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination mock_enricher_test.go -package poller github.com/afreidah/flight-fetcher/internal/enricher Interface
//

// Package poller is a generated GoMock package.
package poller

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Enrich mocks base method.
func (m *MockInterface) Enrich(ctx context.Context, icao24 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrich", ctx, icao24)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enrich indicates an expected call of Enrich.
func (mr *MockInterfaceMockRecorder) Enrich(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrich", reflect.TypeOf((*MockInterface)(nil).Enrich), ctx, icao24)
}

// EnrichRoute mocks base method.
func (m *MockInterface) EnrichRoute(ctx context.Context, callsign string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichRoute", ctx, callsign)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnrichRoute indicates an expected call of EnrichRoute.
func (mr *MockInterfaceMockRecorder) EnrichRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichRoute", reflect.TypeOf((*MockInterface)(nil).EnrichRoute), ctx, callsign)
}
