// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/flight-fetcher/internal/poller (interfaces: FlightSource,FlightCache,SightingLogger)
//
// Generated by this command:
//
//	mockgen -destination mock_poller_test.go -package poller github.com/afreidah/flight-fetcher/internal/poller FlightSource,FlightCache,SightingLogger
//

// Package poller is a generated GoMock package.
package poller

import (
	context "context"
	reflect "reflect"
	time "time"

	opensky "github.com/afreidah/flight-fetcher/internal/apiclient/opensky"
	geo "github.com/afreidah/flight-fetcher/internal/geo"
	gomock "go.uber.org/mock/gomock"
)

// MockFlightSource is a mock of FlightSource interface.
type MockFlightSource struct {
	ctrl     *gomock.Controller
	recorder *MockFlightSourceMockRecorder
	isgomock struct{}
}

// MockFlightSourceMockRecorder is the mock recorder for MockFlightSource.
type MockFlightSourceMockRecorder struct {
	mock *MockFlightSource
}

// NewMockFlightSource creates a new mock instance.
func NewMockFlightSource(ctrl *gomock.Controller) *MockFlightSource {
	mock := &MockFlightSource{ctrl: ctrl}
	mock.recorder = &MockFlightSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightSource) EXPECT() *MockFlightSourceMockRecorder {
	return m.recorder
}

// GetStates mocks base method.
func (m *MockFlightSource) GetStates(ctx context.Context, bbox geo.BBox) (*opensky.StatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStates", ctx, bbox)
	ret0, _ := ret[0].(*opensky.StatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStates indicates an expected call of GetStates.
func (mr *MockFlightSourceMockRecorder) GetStates(ctx, bbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStates", reflect.TypeOf((*MockFlightSource)(nil).GetStates), ctx, bbox)
}

// MockFlightCache is a mock of FlightCache interface.
type MockFlightCache struct {
	ctrl     *gomock.Controller
	recorder *MockFlightCacheMockRecorder
	isgomock struct{}
}

// MockFlightCacheMockRecorder is the mock recorder for MockFlightCache.
type MockFlightCacheMockRecorder struct {
	mock *MockFlightCache
}

// NewMockFlightCache creates a new mock instance.
func NewMockFlightCache(ctrl *gomock.Controller) *MockFlightCache {
	mock := &MockFlightCache{ctrl: ctrl}
	mock.recorder = &MockFlightCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightCache) EXPECT() *MockFlightCacheMockRecorder {
	return m.recorder
}

// MarkHeard mocks base method.
func (m *MockFlightCache) MarkHeard(ctx context.Context, source, icao24 string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkHeard", ctx, source, icao24, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkHeard indicates an expected call of MarkHeard.
func (mr *MockFlightCacheMockRecorder) MarkHeard(ctx, source, icao24, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkHeard", reflect.TypeOf((*MockFlightCache)(nil).MarkHeard), ctx, source, icao24, ttl)
}

// SetFlight mocks base method.
func (m *MockFlightCache) SetFlight(ctx context.Context, sv *opensky.StateVector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFlight", ctx, sv)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFlight indicates an expected call of SetFlight.
func (mr *MockFlightCacheMockRecorder) SetFlight(ctx, sv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlight", reflect.TypeOf((*MockFlightCache)(nil).SetFlight), ctx, sv)
}

// MockSightingLogger is a mock of SightingLogger interface.
type MockSightingLogger struct {
	ctrl     *gomock.Controller
	recorder *MockSightingLoggerMockRecorder
	isgomock struct{}
}

// MockSightingLoggerMockRecorder is the mock recorder for MockSightingLogger.
type MockSightingLoggerMockRecorder struct {
	mock *MockSightingLogger
}

// NewMockSightingLogger creates a new mock instance.
func NewMockSightingLogger(ctrl *gomock.Controller) *MockSightingLogger {
	mock := &MockSightingLogger{ctrl: ctrl}
	mock.recorder = &MockSightingLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSightingLogger) EXPECT() *MockSightingLoggerMockRecorder {
	return m.recorder
}

// LogSighting mocks base method.
func (m *MockSightingLogger) LogSighting(ctx context.Context, icao24 string, lat, lon, distanceKm float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSighting", ctx, icao24, lat, lon, distanceKm)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogSighting indicates an expected call of LogSighting.
func (mr *MockSightingLoggerMockRecorder) LogSighting(ctx, icao24, lat, lon, distanceKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSighting", reflect.TypeOf((*MockSightingLogger)(nil).LogSighting), ctx, icao24, lat, lon, distanceKm)
}
