// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/afreidah/flight-fetcher/internal/poller (interfaces: FlightSource,FlightCache,SightingLogger,FlightEnricher)
//
// Generated by this command:
//
//	mockgen -destination mock_poller_test.go -package poller github.com/afreidah/flight-fetcher/internal/poller FlightSource,FlightCache,SightingLogger,FlightEnricher
//

// Package poller is a generated GoMock package.
package poller

import (
	context "context"
	reflect "reflect"

	geo "github.com/afreidah/flight-fetcher/internal/geo"
	opensky "github.com/afreidah/flight-fetcher/internal/opensky"
	gomock "go.uber.org/mock/gomock"
)

// MockFlightSource is a mock of FlightSource interface.
type MockFlightSource struct {
	ctrl     *gomock.Controller
	recorder *MockFlightSourceMockRecorder
	isgomock struct{}
}

// MockFlightSourceMockRecorder is the mock recorder for MockFlightSource.
type MockFlightSourceMockRecorder struct {
	mock *MockFlightSource
}

// NewMockFlightSource creates a new mock instance.
func NewMockFlightSource(ctrl *gomock.Controller) *MockFlightSource {
	mock := &MockFlightSource{ctrl: ctrl}
	mock.recorder = &MockFlightSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightSource) EXPECT() *MockFlightSourceMockRecorder {
	return m.recorder
}

// GetStates mocks base method.
func (m *MockFlightSource) GetStates(ctx context.Context, bbox geo.BBox) (*opensky.StatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStates", ctx, bbox)
	ret0, _ := ret[0].(*opensky.StatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStates indicates an expected call of GetStates.
func (mr *MockFlightSourceMockRecorder) GetStates(ctx, bbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStates", reflect.TypeOf((*MockFlightSource)(nil).GetStates), ctx, bbox)
}

// MockFlightCache is a mock of FlightCache interface.
type MockFlightCache struct {
	ctrl     *gomock.Controller
	recorder *MockFlightCacheMockRecorder
	isgomock struct{}
}

// MockFlightCacheMockRecorder is the mock recorder for MockFlightCache.
type MockFlightCacheMockRecorder struct {
	mock *MockFlightCache
}

// NewMockFlightCache creates a new mock instance.
func NewMockFlightCache(ctrl *gomock.Controller) *MockFlightCache {
	mock := &MockFlightCache{ctrl: ctrl}
	mock.recorder = &MockFlightCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightCache) EXPECT() *MockFlightCacheMockRecorder {
	return m.recorder
}

// SetFlight mocks base method.
func (m *MockFlightCache) SetFlight(ctx context.Context, sv *opensky.StateVector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFlight", ctx, sv)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFlight indicates an expected call of SetFlight.
func (mr *MockFlightCacheMockRecorder) SetFlight(ctx, sv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFlight", reflect.TypeOf((*MockFlightCache)(nil).SetFlight), ctx, sv)
}

// MockSightingLogger is a mock of SightingLogger interface.
type MockSightingLogger struct {
	ctrl     *gomock.Controller
	recorder *MockSightingLoggerMockRecorder
	isgomock struct{}
}

// MockSightingLoggerMockRecorder is the mock recorder for MockSightingLogger.
type MockSightingLoggerMockRecorder struct {
	mock *MockSightingLogger
}

// NewMockSightingLogger creates a new mock instance.
func NewMockSightingLogger(ctrl *gomock.Controller) *MockSightingLogger {
	mock := &MockSightingLogger{ctrl: ctrl}
	mock.recorder = &MockSightingLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSightingLogger) EXPECT() *MockSightingLoggerMockRecorder {
	return m.recorder
}

// LogSighting mocks base method.
func (m *MockSightingLogger) LogSighting(ctx context.Context, icao24 string, lat, lon, distanceKm float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogSighting", ctx, icao24, lat, lon, distanceKm)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogSighting indicates an expected call of LogSighting.
func (mr *MockSightingLoggerMockRecorder) LogSighting(ctx, icao24, lat, lon, distanceKm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogSighting", reflect.TypeOf((*MockSightingLogger)(nil).LogSighting), ctx, icao24, lat, lon, distanceKm)
}

// MockFlightEnricher is a mock of FlightEnricher interface.
type MockFlightEnricher struct {
	ctrl     *gomock.Controller
	recorder *MockFlightEnricherMockRecorder
	isgomock struct{}
}

// MockFlightEnricherMockRecorder is the mock recorder for MockFlightEnricher.
type MockFlightEnricherMockRecorder struct {
	mock *MockFlightEnricher
}

// NewMockFlightEnricher creates a new mock instance.
func NewMockFlightEnricher(ctrl *gomock.Controller) *MockFlightEnricher {
	mock := &MockFlightEnricher{ctrl: ctrl}
	mock.recorder = &MockFlightEnricherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlightEnricher) EXPECT() *MockFlightEnricherMockRecorder {
	return m.recorder
}

// Enrich mocks base method.
func (m *MockFlightEnricher) Enrich(ctx context.Context, icao24 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enrich", ctx, icao24)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enrich indicates an expected call of Enrich.
func (mr *MockFlightEnricherMockRecorder) Enrich(ctx, icao24 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enrich", reflect.TypeOf((*MockFlightEnricher)(nil).Enrich), ctx, icao24)
}

// EnrichRoute mocks base method.
func (m *MockFlightEnricher) EnrichRoute(ctx context.Context, callsign string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnrichRoute", ctx, callsign)
	ret0, _ := ret[0].(bool)
	return ret0
}

// EnrichRoute indicates an expected call of EnrichRoute.
func (mr *MockFlightEnricherMockRecorder) EnrichRoute(ctx, callsign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnrichRoute", reflect.TypeOf((*MockFlightEnricher)(nil).EnrichRoute), ctx, callsign)
}
