// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aircraft.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAircraftMeta = `-- name: GetAircraftMeta :one
SELECT icao24, registration, manufacturer, type, operator, icao_type_code, registered_owners, image_url
FROM aircraft_meta
WHERE icao24 = $1 AND updated_at > $2
`

type GetAircraftMetaParams struct {
	Icao24    string
	UpdatedAt pgtype.Timestamptz
}

type GetAircraftMetaRow struct {
	Icao24           string
	Registration     string
	Manufacturer     string
	Type             string
	Operator         string
	IcaoTypeCode     string
	RegisteredOwners string
	ImageUrl         string
}

func (q *Queries) GetAircraftMeta(ctx context.Context, arg GetAircraftMetaParams) (GetAircraftMetaRow, error) {
	row := q.db.QueryRow(ctx, getAircraftMeta, arg.Icao24, arg.UpdatedAt)
	var i GetAircraftMetaRow
	err := row.Scan(
		&i.Icao24,
		&i.Registration,
		&i.Manufacturer,
		&i.Type,
		&i.Operator,
		&i.IcaoTypeCode,
		&i.RegisteredOwners,
		&i.ImageUrl,
	)
	return i, err
}

const upsertAircraftMeta = `-- name: UpsertAircraftMeta :exec
INSERT INTO aircraft_meta (icao24, registration, manufacturer, type, operator, icao_type_code, registered_owners, image_url, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (icao24) DO UPDATE SET
    registration = EXCLUDED.registration,
    manufacturer = EXCLUDED.manufacturer,
    type = EXCLUDED.type,
    operator = EXCLUDED.operator,
    icao_type_code = EXCLUDED.icao_type_code,
    registered_owners = EXCLUDED.registered_owners,
    image_url = EXCLUDED.image_url,
    updated_at = now()
`

type UpsertAircraftMetaParams struct {
	Icao24           string
	Registration     string
	Manufacturer     string
	Type             string
	Operator         string
	IcaoTypeCode     string
	RegisteredOwners string
	ImageUrl         string
}

func (q *Queries) UpsertAircraftMeta(ctx context.Context, arg UpsertAircraftMetaParams) error {
	_, err := q.db.Exec(ctx, upsertAircraftMeta,
		arg.Icao24,
		arg.Registration,
		arg.Manufacturer,
		arg.Type,
		arg.Operator,
		arg.IcaoTypeCode,
		arg.RegisteredOwners,
		arg.ImageUrl,
	)
	return err
}
