// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aircraft.sql

package db

import (
	"context"
)

const getAircraftMeta = `-- name: GetAircraftMeta :one
SELECT icao24, registration, manufacturer, type, operator
FROM aircraft_meta
WHERE icao24 = $1
`

type GetAircraftMetaRow struct {
	Icao24       string
	Registration string
	Manufacturer string
	Type         string
	Operator     string
}

func (q *Queries) GetAircraftMeta(ctx context.Context, icao24 string) (GetAircraftMetaRow, error) {
	row := q.db.QueryRow(ctx, getAircraftMeta, icao24)
	var i GetAircraftMetaRow
	err := row.Scan(
		&i.Icao24,
		&i.Registration,
		&i.Manufacturer,
		&i.Type,
		&i.Operator,
	)
	return i, err
}

const upsertAircraftMeta = `-- name: UpsertAircraftMeta :exec
INSERT INTO aircraft_meta (icao24, registration, manufacturer, type, operator, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (icao24) DO UPDATE SET
    registration = EXCLUDED.registration,
    manufacturer = EXCLUDED.manufacturer,
    type = EXCLUDED.type,
    operator = EXCLUDED.operator,
    updated_at = now()
`

type UpsertAircraftMetaParams struct {
	Icao24       string
	Registration string
	Manufacturer string
	Type         string
	Operator     string
}

func (q *Queries) UpsertAircraftMeta(ctx context.Context, arg UpsertAircraftMetaParams) error {
	_, err := q.db.Exec(ctx, upsertAircraftMeta,
		arg.Icao24,
		arg.Registration,
		arg.Manufacturer,
		arg.Type,
		arg.Operator,
	)
	return err
}
