// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AircraftMetum struct {
	Icao24       string
	Registration string
	Manufacturer string
	Type         string
	Operator     string
}

type FlightRoute struct {
	Callsign string
	DepIata  string
	DepIcao  string
	DepName  string
	ArrIata  string
	ArrIcao  string
	ArrName  string
	CachedAt pgtype.Timestamptz
}

type Sighting struct {
	ID         int64
	Icao24     string
	Lat        float64
	Lon        float64
	DistanceKm float64
	SeenAt     pgtype.Timestamptz
}

type SquawkAlert struct {
	ID       int64
	Icao24   string
	Callsign string
	Squawk   string
	Lat      float64
	Lon      float64
	SeenAt   pgtype.Timestamptz
}
