// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldRoutes = `-- name: DeleteOldRoutes :execresult
DELETE FROM flight_routes WHERE callsign IN (
    SELECT r.callsign FROM flight_routes r WHERE r.cached_at < $1 LIMIT 10000
)
`

func (q *Queries) DeleteOldRoutes(ctx context.Context, cachedAt pgtype.Timestamptz) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldRoutes, cachedAt)
}

const getFlightRoute = `-- name: GetFlightRoute :one
SELECT callsign, dep_iata, dep_icao, dep_name, arr_iata, arr_icao, arr_name
FROM flight_routes
WHERE callsign = $1 AND cached_at > $2
`

type GetFlightRouteParams struct {
	Callsign string
	CachedAt pgtype.Timestamptz
}

type GetFlightRouteRow struct {
	Callsign string
	DepIata  string
	DepIcao  string
	DepName  string
	ArrIata  string
	ArrIcao  string
	ArrName  string
}

func (q *Queries) GetFlightRoute(ctx context.Context, arg GetFlightRouteParams) (GetFlightRouteRow, error) {
	row := q.db.QueryRow(ctx, getFlightRoute, arg.Callsign, arg.CachedAt)
	var i GetFlightRouteRow
	err := row.Scan(
		&i.Callsign,
		&i.DepIata,
		&i.DepIcao,
		&i.DepName,
		&i.ArrIata,
		&i.ArrIcao,
		&i.ArrName,
	)
	return i, err
}

const upsertFlightRoute = `-- name: UpsertFlightRoute :exec
INSERT INTO flight_routes (callsign, dep_iata, dep_icao, dep_name, arr_iata, arr_icao, arr_name, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (callsign) DO UPDATE SET
    dep_iata = EXCLUDED.dep_iata,
    dep_icao = EXCLUDED.dep_icao,
    dep_name = EXCLUDED.dep_name,
    arr_iata = EXCLUDED.arr_iata,
    arr_icao = EXCLUDED.arr_icao,
    arr_name = EXCLUDED.arr_name,
    cached_at = now()
`

type UpsertFlightRouteParams struct {
	Callsign string
	DepIata  string
	DepIcao  string
	DepName  string
	ArrIata  string
	ArrIcao  string
	ArrName  string
}

func (q *Queries) UpsertFlightRoute(ctx context.Context, arg UpsertFlightRouteParams) error {
	_, err := q.db.Exec(ctx, upsertFlightRoute,
		arg.Callsign,
		arg.DepIata,
		arg.DepIcao,
		arg.DepName,
		arg.ArrIata,
		arg.ArrIcao,
		arg.ArrName,
	)
	return err
}
