// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"
)

const getFlightRoute = `-- name: GetFlightRoute :one
SELECT callsign, dep_iata, dep_icao, dep_name, arr_iata, arr_icao, arr_name
FROM flight_routes
WHERE callsign = $1
`

func (q *Queries) GetFlightRoute(ctx context.Context, callsign string) (FlightRoute, error) {
	row := q.db.QueryRow(ctx, getFlightRoute, callsign)
	var i FlightRoute
	err := row.Scan(
		&i.Callsign,
		&i.DepIata,
		&i.DepIcao,
		&i.DepName,
		&i.ArrIata,
		&i.ArrIcao,
		&i.ArrName,
	)
	return i, err
}

const upsertFlightRoute = `-- name: UpsertFlightRoute :exec
INSERT INTO flight_routes (callsign, dep_iata, dep_icao, dep_name, arr_iata, arr_icao, arr_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (callsign) DO UPDATE SET
    dep_iata = EXCLUDED.dep_iata,
    dep_icao = EXCLUDED.dep_icao,
    dep_name = EXCLUDED.dep_name,
    arr_iata = EXCLUDED.arr_iata,
    arr_icao = EXCLUDED.arr_icao,
    arr_name = EXCLUDED.arr_name
`

type UpsertFlightRouteParams struct {
	Callsign string
	DepIata  string
	DepIcao  string
	DepName  string
	ArrIata  string
	ArrIcao  string
	ArrName  string
}

func (q *Queries) UpsertFlightRoute(ctx context.Context, arg UpsertFlightRouteParams) error {
	_, err := q.db.Exec(ctx, upsertFlightRoute,
		arg.Callsign,
		arg.DepIata,
		arg.DepIcao,
		arg.DepName,
		arg.ArrIata,
		arg.ArrIcao,
		arg.ArrName,
	)
	return err
}
