// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sightings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldSightings = `-- name: DeleteOldSightings :execresult
DELETE FROM sightings WHERE seen_at < $1
`

func (q *Queries) DeleteOldSightings(ctx context.Context, seenAt pgtype.Timestamptz) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldSightings, seenAt)
}

const logSighting = `-- name: LogSighting :exec
INSERT INTO sightings (icao24, lat, lon, distance_km, seen_at)
VALUES ($1, $2, $3, $4, $5)
`

type LogSightingParams struct {
	Icao24     string
	Lat        float64
	Lon        float64
	DistanceKm float64
	SeenAt     pgtype.Timestamptz
}

func (q *Queries) LogSighting(ctx context.Context, arg LogSightingParams) error {
	_, err := q.db.Exec(ctx, logSighting,
		arg.Icao24,
		arg.Lat,
		arg.Lon,
		arg.DistanceKm,
		arg.SeenAt,
	)
	return err
}
