// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: squawk_alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldSquawkAlerts = `-- name: DeleteOldSquawkAlerts :execresult
DELETE FROM squawk_alerts WHERE seen_at < $1
`

func (q *Queries) DeleteOldSquawkAlerts(ctx context.Context, seenAt pgtype.Timestamptz) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldSquawkAlerts, seenAt)
}

const getRecentSquawkAlerts = `-- name: GetRecentSquawkAlerts :many
SELECT id, icao24, callsign, squawk, lat, lon, seen_at
FROM squawk_alerts
WHERE seen_at > $1
ORDER BY seen_at DESC
`

func (q *Queries) GetRecentSquawkAlerts(ctx context.Context, seenAt pgtype.Timestamptz) ([]SquawkAlert, error) {
	rows, err := q.db.Query(ctx, getRecentSquawkAlerts, seenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SquawkAlert{}
	for rows.Next() {
		var i SquawkAlert
		if err := rows.Scan(
			&i.ID,
			&i.Icao24,
			&i.Callsign,
			&i.Squawk,
			&i.Lat,
			&i.Lon,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSquawkAlert = `-- name: InsertSquawkAlert :exec
INSERT INTO squawk_alerts (icao24, callsign, squawk, lat, lon, seen_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSquawkAlertParams struct {
	Icao24   string
	Callsign string
	Squawk   string
	Lat      float64
	Lon      float64
	SeenAt   pgtype.Timestamptz
}

func (q *Queries) InsertSquawkAlert(ctx context.Context, arg InsertSquawkAlertParams) error {
	_, err := q.db.Exec(ctx, insertSquawkAlert,
		arg.Icao24,
		arg.Callsign,
		arg.Squawk,
		arg.Lat,
		arg.Lon,
		arg.SeenAt,
	)
	return err
}
